# Generated by Django 5.0.3 on 2024-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat', models.CharField(choices=[('Nedumbassery', 'Nedumbassery'), ('Kuthiyathode', 'Kuthiyathode'), ('Parakkadavu', 'Parakkadavu'), ('Chengamanad', 'Chengamanad'), ('Puthenvelikkara', 'Puthenvelikkara'), ('Sreemoolangaram', 'Sreemoolangaram')], default='Nedumbassery', max_length=100)),
                ('ward', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='profile')),
                ('proof', models.ImageField(upload_to='proof')),
            ],
        ),
    ]
