# Generated by Django 5.0.3 on 2024-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
