# Generated by Django 5.0.3 on 2024-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_alter_usersignup_proof_alter_usersignup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaintimage',
            field=models.ImageField(null=True, upload_to='complaint'),
        ),
    ]
