# Generated by Django 5.0.3 on 2024-03-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
