# Generated by Django 5.0.3 on 2024-03-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('complaintimage', models.ImageField(null=True, upload_to='complaint')),
                ('complaintstatus', models.CharField(choices=[('Pending', 'Pending'), ('Action Taken', 'Action Taken'), ('Solved', 'Solved')], default='Pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=1000)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.usersignup')),
            ],
        ),
    ]
