# Generated by Django 5.0.3 on 2024-03-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_delete_complaint_delete_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat', models.CharField(choices=[('Nedumbassery', 'Nedumbassery'), ('Kuthiyathode', 'Kuthiyathode'), ('Parakkadavu', 'Parakkadavu'), ('Chengamanad', 'Chengamanad'), ('Puthenvelikkara', 'Puthenvelikkara'), ('Sreemoolangaram', 'Sreemoolangaram')], default='Nedumbassery', max_length=100)),
                ('ward', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('proof', models.ImageField(null=True, upload_to='proof')),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('complaintimage', models.ImageField(null=True, upload_to='complaint')),
                ('complaintstatus', models.CharField(choices=[('Pending', 'Pending'), ('Action Taken', 'Action Taken'), ('Solved', 'Solved')], default='Pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.usersignup')),
            ],
        ),
    ]
