# Generated by Django 5.0.3 on 2024-03-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0014_usersignup_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blockk',
        ),
    ]
