# Generated by Django 5.0.3 on 2024-03-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0016_blockk_alter_usersignup_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.DeleteModel(
            name='usersignup',
        ),
    ]
