# Generated by Django 5.0.3 on 2024-03-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0019_delete_complaintimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintimages', models.ImageField(null=True, upload_to='complaintimages')),
                ('cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.complaint')),
            ],
        ),
    ]
