# Generated by Django 4.2.5 on 2024-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0020_complaintimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='image',
            field=models.ImageField(default='img/noprofile.jpg', null=True, upload_to='profile'),
        ),
    ]
