# Generated by Django 5.0.3 on 2024-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0022_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
