# Generated by Django 5.0.4 on 2024-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0024_complaintmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='smailact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='smailp',
            field=models.IntegerField(default=0),
        ),
    ]
